# Generated by Django 3.1.1 on 2021-10-10 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.FileField(upload_to='mods_files/')),
            ],
        ),
        migrations.CreateModel(
            name='HaveMod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mods', models.ManyToManyField(blank=True, to='mods.Mod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.discorduser')),
            ],
        ),
    ]
